name: Auto Publish Specific Article

on:
  push:
    branches:
      - develop 

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Get list of changed files
        id: get-changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'articles/.*\.md$')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No article files were changed."
            exit 0
          fi
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Update 'published' status for changed articles
        run: |
          for file in $CHANGED_FILES; do
            if grep -q "published: false" "$file"; then
              sed -i 's/published: false/published: true/' "$file"
            fi
          done

      - name: Commit and push if changes are detected
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          git commit -m 'Auto-publish articles' || exit 0   # Exit gracefully if no changes
          git push
