name: Auto Publish Specific Article

on:
  push:
    branches:
      - develop

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # リポジトリのすべての履歴をフェッチ

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Get list of changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'articles/.*\.md$' > changed_files.txt

      - name: Show changed files
        run: cat changed_files.txt

      - name: Update 'published' status for changed articles
        run: |
          while IFS= read -r file; do
            if [ ! -f "$file" ]; then
              echo "$file does not exist."
              continue
            fi
            echo "Processing $file"
            sed -i '/^published: false$/s/false/true/' "$file"
          done < changed_files.txt


      - name: Commit and push if changes are detected
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          git commit -m 'Auto-publish articles' -m '[skip ci]' || exit 0
          git push --set-upstream origin HEAD:develop --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
